name: Renode linux tester
inputs:
  renode-run:
    description: Command or a list of commands to run in Renode
    required: true
  shared-dirs:
    description: Paths to shared directories
    required: false
    default:
  shared-dir:
    description: Path to shared directory (deprecated)
    required: false
    default: ""
  devices:
    description: Devices to set up
    required: false
    default: ""
  image:
    description: Compiled linux image source
    required: false
    default: ""
  python-packages:
    description: Custom python packages that will be sideloaded to emulated Linux
    required: false
    default: ""
  repos:
    description: Custom git repos that will be added to your shared dir
    required: false
    default: ""
  network:
    description: Enable network in the emulated Linux? true/false
    required: false
    default: true
  rootfs-size:
    description: Rootfs size
    required: false
    default: "auto"
runs:
  using: composite
  steps:

    - id: check-required-python-version
      run: |
        printf -v VERSIONS '%s\n%s' "$(python3 --version | awk '{ print $2 }')" "3.9"
        if [[ "$VERSIONS" = "$(sort -V <<< "$VERSIONS")" ]]; then
          echo "Minimum Python version required is 3.9"
          exit 1
        fi
      shell: bash

    - id: create-working-directory
      run: |
        mkdir -p ${GITHUB_ACTION_PATH}
      shell: bash

    - id: get-images
      run: |
        if [ -z "$IMAGE" ]; then
          IMAGE="https://github.com/$ACTION_REPO/releases/download/$ACTION_REF/images.tar.xz"
        fi
        if [ -f "$IMAGE" ] && [ $(realpath "$IMAGE") == "$(realpath ${GITHUB_ACTION_PATH}/images.tar.xz)" ]; then
          echo File already exists
        elif [ -f "$IMAGE" ]; then
          cp "$IMAGE" ${GITHUB_ACTION_PATH}/images.tar.xz
        else
          wget -q --no-verbose "$IMAGE" -O ${GITHUB_ACTION_PATH}/images.tar.xz
        fi
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        # https://github.com/orgs/community/discussions/49245
        ACTION_REPO: ${{ github.action_repository || github.repository }}
        ACTION_REF: ${{ github.action_ref || github.ref_name }}

    - id: decompress
      run: cd ${GITHUB_ACTION_PATH} && tar xf images.tar.xz
      shell: bash

    - id: install-packages
      run: |
        wget -q --no-verbose https://github.com/renode/renode/releases/download/v1.13.3/renode_1.13.3_amd64.deb && \
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends                             \
        ./renode_1.13.3_amd64.deb python3-venv
      shell: bash

    - id: install-pip-packages
      run: pip3 install -r ${GITHUB_ACTION_PATH}/requirements.txt
      shell: bash

    - id: create-pip-virtual-environment
      run: cd ${GITHUB_ACTION_PATH} && mkdir -p venv-dir && python3 -m venv venv-dir
      shell: bash

    - id: test
      run: |
        cd ${GITHUB_ACTION_PATH} && sudo python3 action/run-in-renode.py \
        '${{ toJSON(inputs) }}' "${GITHUB_WORKSPACE}"
      shell: bash
