name: Renode linux tester
inputs:
  shared-dir:
    description: Path to shared directory
    required: true
  renode-run:
    description: Command or a list of commands to run in Renode
    required: true
  devices:
    description: Devices to set up
    required: false
    default: ""
  image:
    description: Compiled linux image source
    required: false
    default: "https://github.com/antmicro/renode-linux-runner-action/releases/download/latest/images.tar.xz"
  python-packages:
    description: Custom python packages that will be added to your shared dir
    required: false
    default: ""
  repos:
    description: Custom git repos that will be added to your shared dir
    required: false
    default: ""
runs:
  using: composite
  steps:

    - id: copy-user-path
      run: |
        sudo mkdir -p ${{github.action_path}} &&           \
        sudo mkdir -p /mnt/user &&                         \
        sudo cp -r "${{ inputs.shared-dir }}"/* /mnt/user
      shell: bash

    - id: get-images
      run: |
        if [ -f "${{ inputs.image }}" ] && [ $(realpath "${{ inputs.image }}") == "$(realpath ${{github.action_path}}/images.tar.xz)" ]; then \
          echo File already exists;                                                                                                           \
        elif [ -f "${{ inputs.image }}" ]; then                                                                                               \
          cp "${{ inputs.image }}" ${{github.action_path}}/images.tar.xz;                                                                     \
        else                                                                                                                                  \
          wget -q --no-verbose "${{ inputs.image }}" -O ${{github.action_path}}/images.tar.xz;                                                \
        fi
      shell: bash

    - id: decompress
      run: cd ${{github.action_path}} && tar xf images.tar.xz
      shell: bash

    - id: install-packages
      run: |
        wget -q --no-verbose https://github.com/renode/renode/releases/download/v1.13.3/renode_1.13.3_amd64.deb && \
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends                             \
        ./renode_1.13.3_amd64.deb python3-venv
      shell: bash

    - id: install-pip-packages
      run: pip3 install pexpect virtualenv
      shell: bash

    - id: create-pip-virtual-environment
      run: cd ${{github.action_path}} && mkdir -p venv-dir && python3 -m venv venv-dir
      shell: bash

    - id: test
      run: |
        cd ${{github.action_path}} && sudo python3 action/run-in-renode.py \
        "${{ inputs.renode-run }}"                                         \
        "${{ inputs.devices }}"                                            \
        "${{ inputs.python-packages }}"                                    \
        "${{ inputs.repos }}"
      shell: bash
