name: 'Renode linux tester'
inputs:
  shared-dir:
    description: 'Shared directory'
    required: true
  renode-run:
    required: true
runs:
  using: docker
  image: docker://ghcr.io/antmicro/renode-gha-linux-playground/renode-linux-tester
  args:
    - ${{ inputs.shared-dir }}
    - ${{ inputs.renode-run }}
