# Co-authored by: Unai Martinez-Corral (@umarcor)
name: Build docker container
on:
  push:
    paths:
      - 'renode-linux-runner-docker/**'
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build -t ghcr.io/${{ github.repository }} renode-linux-runner-docker
      - name: Login to ghcr.io and release
        uses: pyTooling/Actions/with-post-step@r0
        with:
          main: |
            echo '${{ github.token }}' | docker login ghcr.io -u gha --password-stdin
            docker push ghcr.io/${{ github.repository }}
          post: docker logout ghcr.io
