name: Build and test on pull request
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get packages
        if: ${{ env.ACT }}
        run: |
         sudo apt update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
         python3-pip telnet iptables iproute2 bc cpio rsync

      - name: build kernel
        run: ./scripts/compile.sh

      - name: test
        uses: ./
        with:
          shared-dir: ./tests
          image: ./images.tar.xz
          renode-run: |
            wget example.org
            gpiodetect
            sh gpio.sh
            sh i2c.sh
            python pyrav4l2/.github/save_examples.py pyrav4l2/README.md
            python examples/controls-enumeration.py
          devices: |
            vivid
            gpio 0 16
            i2c 0x1C
          python-packages: |
            git+https://github.com/antmicro/pyrav4l2.git@3c071a7494b6b67263c4dddb87b47025338fd960
            git+https://github.com/antmicro/tuttest.git@c44309e0365c54759fb36864fb77bf8b347bd647
          repos: https://github.com/antmicro/pyrav4l2.git pyrav4l2
